### ISSUE TITLE
contenthash not working in aggregateFilename

### ISSUE THREAD

**Issue by bf** [maniax89/react-intl-aggregate-webpack-plugin#3]
When I set `aggregateFilename: "en.[contenthash].json"` it is not using contenthash as other webpack plugins do. Is it possible to enable this feature?

**Comment by maniax89** [comment]
I think you are referring to the `TemplatedPathPlugin` -> https://github.com/webpack/webpack/blob/master/lib/TemplatedPathPlugin.js

From the [documentation](https://webpack.js.org/configuration/output/#output-filename), it states:

> The following substitutions are available in template strings (via webpack's internal TemplatedPathPlugin):
> 
> | Template | Description |
> | --- | --- |
> |[hash]|The hash of the module identifier|
> |[chunkhash]|The hash of the chunk content|
> |[name]|The module name|
> |[id]|The module identifier|
> |[query]|The module query, i.e., the string following ? in the filename|
> 
> When using the [ExtractTextWebpackPlugin](https://webpack.js.org/plugins/extract-text-webpack-plugin/), use [contenthash] to obtain a hash of the extracted file (neither [hash] nor [chunkhash] work).

Based on that - it seems only the `ExtractTextWebpackPlugin` enables this feature. If you want to submit a PR to implement it (seems like the relevant code is https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/master/src/index.js#L207-L211) I would accept it probably.

**Comment by bf** [comment]
Thanks for your quick response @maniax89, I have used a static filename instead.
